### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by RoiEXLab**

### CODE REVIEW

**Review by ssoloff — COMMENTED** [review]
Just want to confirm all the whitespace changes in this PR were intentional.  It looks like the EOL terminators were changed from LF to CRLF.

**Comment by RoiEXLab** [comment]
@ssoloff Not intentional at all, updated!
The weird thing is that I used to online editor for those changes.

**Comment by RoiEXLab** [comment]
@ssoloff Ahh looks like the line endings were mixed or something, that's probably why the online editor assumed it was CRLF

**Comment by ssoloff** [comment]
@RoiEXLab Ok, just to confirm...  the remaining whitespace-only changes _are_ intentional and simply make all line endings consistent?

**Comment by RoiEXLab** [comment]
@ssoloff Yes

**Review by ssoloff — APPROVED** [review]

**Comment by RoiEXLab** [comment]
@ssoloff Was that the last PR? I lost track of them 😅

**Comment by ssoloff** [comment]
@RoiEXLab I believe so.

**Pull request merged**
